[tool.poetry]
name = "extract2024"
version = "0.1.0"
description = ""
authors = ["Pedro Perez de Ayala <ppayala@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
